### ISSUE TITLE
Send last_modified to server

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-client#1]
If a record has a `last_modified` field, we should:
* use it for the `ETag` value
* send it in the body

The server will ignore the provided value and bump the timestamp as usual.
If the last_modified value provided is not equal to the one being stored on the server, it will raise a 412 anyway.

> If we want to be able to force the last_modified value from the client (ex. data replication) that's another story (still possible if the provided timestamp is higher than the current one and no ETag header is sent)

**Comment by n1k0** [comment]
@leplatrem I'm having hard times remembering what should be precisely done in code here, could you please check current code to see if this is still needed? Thanks.

**Comment by leplatrem** [comment]
There used to be a *clean record* function that was always removing the `last_modified` field.

From what I read in the code, it's not the case anymore. Closing.
