### ISSUE TITLE
When doing `CORS`, an `OPTION` request is done on the `unknown` bucket

### ISSUE THREAD

**Issue by almet** [Kinto/kinto-client#30]
Logs from the server:

```
OPTIONS /v1/buckets/unknown/collections" 200 (2 ms)
POST  /v1/buckets/51753f73-0f62-3c2e-10ab-99cc880a09e5/collections" 201 (12 ms)
```

**Comment by n1k0** [comment]
How is this related to this javascript client? The unknown string is missing from the whole codebase :)

**Comment by Natim** [comment]
Isn't it something that we should investigate nevertheless?

**Comment by n1k0** [comment]
How could it be related to client side code? I mean that's an invalid endpoint path and the only occurrence of `"unknown"` is in server code: https://github.com/Kinto/kinto/blob/4cc3e9d7259e9c74260d6e666cfc72a7046eff33/kinto/plugins/default_bucket/__init__.py#L84-L86

**Comment by Natim** [comment]
Then you did investigate :+1: It is a server feature :)
