### ISSUE TITLE
Handle minor changes between kinto protocol versions

### ISSUE THREAD

**Issue by almet** [Kinto/kinto-client#62]
Currently, minor version changes in the Kinto protocol can introduce new features (e.g. a new delete buckets endpoint).

We can end up in a state where a new Kinto client (e.g. supporting Kinto protocol v1.4) tries to talk with a server which supports an older version of the protocol (e.g. v1.3), resulting in errors (e.g. HTTP 405 if the method doesn't exist on the endpoint, etc.).

To avoid having this behaviour, it is possible to have the client check if the operation is supported by the server (by comparing the server and client protocol versions).

**Comment by n1k0** [comment]
You mentioned decorators this morning, and I think it would make sense to use them here indeed:

```
  @support(">=1.4<2")
  deleteBuckets(id, options) {
    ...
  }
```

**Comment by almet** [comment]
Oh, really cool. That's the "new awesome ES7 feature" I was expecting this morning. Can we use it yet with Babel?

**Comment by n1k0** [comment]
Yes, by enabling a plugin :)

**Comment by almet** [comment]
So, this looks like a good way to do it. A few minor tweaks:

-  It probably should just define what is the minimal needed version on the server, eg. `@introducedIn("1.4")`;
- We will stil need to have the current server protocol version to do the comparison and issue an error. How do you envision retrieving it in the decorator?

**Comment by n1k0** [comment]
Enabling decorator syntax is trickier than expected :( https://phabricator.babeljs.io/T2648

**Comment by almet** [comment]
Yeah, that seems a good way to do it (what we were discussing when eating with @natim not knowing the existence of ES7 decorators)
