### ISSUE TITLE
Do not send the data when deleting resources

### ISSUE THREAD

**Issue by almet** [Kinto/kinto-client#64]
Currently, [the code is sending a body attribute in the delete requests](https://github.com/Kinto/kinto-client/blob/64f74f4abee91e78d838d2751e5bc7d09ab84ddd/src/requests.js#L176-L182). I believe it should be removed.

**Comment by vsham20** [comment]
@almet can I work on this bug?

**Comment by n1k0** [comment]
@vsham20 yes!

**Comment by leplatrem** [comment]
Fixed in #68
