### ISSUE TITLE
Handle arbitrary attributes for buckets

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-client#71]
*(not a priority)* Since protocol `1.4`, buckets can receive arbitrary attributes. `createBucket()` and `updateBucket()` can now receive a data parameter.

**Comment by vsham20** [comment]
@leplatrem can i work on this bug?

**Comment by vsham20** [comment]
@leplatrem Can you explain me the bug and give me some specifics on getting started with this?

**Comment by leplatrem** [comment]
If you look at the methods mentionned in the issue, you will see that they don't have a `data` parameter.

The goal is to add it so that it is possible to create/update bucket objects with custom data (ie. arbitrary attributes). Exactly like `createCollection` or `createRecord`.

**Comment by vsham20** [comment]
@leplatrem as far i understand i have to add a parameter like its done here "https://github.com/Kinto/kinto-client/blob/master/src/requests.js#L201" named "record", so my question is should i name the new parameter to be added as "record" or "data"?

**Comment by leplatrem** [comment]
Yes, you should mimic what's done there indeed. 

I suggest `data` for the name.

**Comment by vsham20** [comment]
@leplatrem cool, thanks

**Comment by n1k0** [comment]
We should also reuse the `setMetadata` setter we use for collections, for consistency.
