### ISSUE TITLE
Consistent naming for collection and bucket methods operating on data 

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto-client#83]
We should rename `getAttributes`, `setMetadata` and friends to just `getData` and `setData` and deprecate these old methods.

**Comment by leplatrem** [comment]
There might be something also around `updateRecord()`,  which could received `data` and `permissions`

**Comment by leplatrem** [comment]
Some additional inconsistencies spotted:

* On collection, there is `createRecord()`, `updateRecord()`, `deleteRecord(). On bucket there is `createCollection()` and `deleteCollection()` but no `updateCollection()`. On base, there is `createBucket()` and `deleteBucket() but no `updateBucket()`.
* unlike `createBucket()` and `createCollection()`, `createRecord()` cannot receive `data` and `permissions` in options
* unlike `createCollection()`, `createBucket()` is not documented as being able to receive `undefined` as first argument
